[General]
backgroundImage=/home/kaemy/.config/quickshell/wallpapers/retro-BMO.png
backgroundColor=#43856c
accentColor=#86d8ab
cardColor=#e643856c
textColor=#2828a5
mutedTextColor=#d0da4b
errorColor=#992c24
fontFamily=GohuFont 14 Nerd Font
welcomeText=BMO
showHostname=true
