[General]
backgroundImage=/home/kaemy/.config/quickshell/wallpapers/marcy.png
backgroundColor=#1A2E4D
accentColor=#B3273B
cardColor=#e61A2E4D
textColor=#E8DDE7
mutedTextColor=#6E3B68
errorColor=#D96B7A
fontFamily=MesloLGM Nerd Font
welcomeText=Marcy
showHostname=true
