[General]
backgroundImage=/home/kaemy/.config/quickshell/wallpapers/IK.png
backgroundColor=#3CA8D7
accentColor=#75DFF0
cardColor=#e63CA8D7
textColor=#092A5B
mutedTextColor=#0000E8
errorColor=#FFD33B
fontFamily=MesloLGSDZ Nerd Font
welcomeText=IK
showHostname=true
